rails_test_app/config/routes.rb
Rails.application.routes.draw do
  resources :test_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_test_app/app/models/test_user.rb
class TestUser < ApplicationRecord
end

rails_test_app/app/models/user.rb
class User < ApplicationRecord
end

rails_test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails_test_app/app/controllers/test_users_controller.rb
class TestUsersController < ApplicationController
  before_action :set_test_user, only: [:show, :edit, :update, :destroy]

  # GET /test_users
  # GET /test_users.json
  def index
    @test_users = TestUser.all
  end

  # GET /test_users/1
  # GET /test_users/1.json
  def show
  end

  # GET /test_users/new
  def new
    @test_user = TestUser.new
  end

  # GET /test_users/1/edit
  def edit
  end

  # POST /test_users
  # POST /test_users.json
  def create
    @test_user = TestUser.new(test_user_params)

    respond_to do |format|
      if @test_user.save
        format.html { redirect_to @test_user, notice: 'Test user was successfully created.' }
        format.json { render :show, status: :created, location: @test_user }
      else
        format.html { render :new }
        format.json { render json: @test_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_users/1
  # PATCH/PUT /test_users/1.json
  def update
    respond_to do |format|
      if @test_user.update(test_user_params)
        format.html { redirect_to @test_user, notice: 'Test user was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_user }
      else
        format.html { render :edit }
        format.json { render json: @test_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_users/1
  # DELETE /test_users/1.json
  def destroy
    @test_user.destroy
    respond_to do |format|
      format.html { redirect_to test_users_url, notice: 'Test user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_user
      @test_user = TestUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_user_params
      params.fetch(:test_user, {})
    end
end

rails_test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_test_app/app/helpers/test_users_helper.rb
module TestUsersHelper
end

rails_test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_test_app/app/views/test_users/_form.html.erb
<%= form_for(test_user) do |f| %>
  <% if test_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_user.errors.count, "error") %> prohibited this test_user from being saved:</h2>

      <ul>
      <% test_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_test_app/app/views/test_users/edit.html.erb
<h1>Editing Test User</h1>

<%= render 'form', test_user: @test_user %>

<%= link_to 'Show', @test_user %> |
<%= link_to 'Back', test_users_path %>

rails_test_app/app/views/test_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_users.each do |test_user| %>
      <tr>
        <td><%= link_to 'Show', test_user %></td>
        <td><%= link_to 'Edit', edit_test_user_path(test_user) %></td>
        <td><%= link_to 'Destroy', test_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test User', new_test_user_path %>

rails_test_app/app/views/test_users/new.html.erb
<h1>New Test User</h1>

<%= render 'form', test_user: @test_user %>

<%= link_to 'Back', test_users_path %>

rails_test_app/app/views/test_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_test_user_path(@test_user) %> |
<%= link_to 'Back', test_users_path %>